import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright';

// Uses only the already-installed browser. Run against Atlas Three's local preview.
const base = process.env.ATLAS_THREE_URL || 'http://127.0.0.1:5187/';
const evidence = fileURLToPath(new URL('../evidence/chat-ui-lab/', import.meta.url));
await mkdir(evidence, { recursive: true });
const browser = await chromium.launch({ headless: true });
const page = await browser.newPage({ viewport: { width: 1600, height: 1100 } });
page.setDefaultTimeout(7000);
const errors = [], requests = [], passed = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => requests.push({ url: request.url(), type: request.resourceType(), method: request.method() }));
const check = (label, value) => { assert.ok(value, label); passed.push(label); console.log(`PASS ${label}`); };
const button = name => page.getByRole('button', { name, exact: true });
const tab = name => page.getByRole('tab', { name, exact: true });
const choose = async (label, option) => {
  await page.getByRole('combobox', { name: label, exact: true }).click();
  await page.getByRole('option', { name: option, exact: true }).click();
};
const timeline = () => page.getByTestId('lab-time').textContent();
const seek = async value => {
  await page.getByRole('slider', { name: 'Timeline', exact: true }).fill(String(value));
};
const snapshot = () => page.locator('[data-transcript="current"] [data-item]').evaluateAll(nodes => nodes.map(node => [node.dataset.item, node.dataset.lifecycle, node.textContent]));
try {
  await page.goto(base);
  await page.getByRole('textbox', { name: 'Project name', exact: true }).fill('Preserved spacing draft');
  await tab('Chat UI Lab').click();
  await page.evaluate(() => { localStorage.setItem('real-chat-sentinel', 'untouched'); sessionStorage.setItem('real-chat-sentinel', 'untouched'); });
  const originalStorage = await page.evaluate(() => [JSON.stringify(localStorage), JSON.stringify(sessionStorage)]);
  check('External scenario panel stays outside product panes', await page.locator('.lab-chat .lab-controls').count() === 0);
  await button('Run scenario').click();
  check('Run scenario reaches real composer send once', await page.getByTestId('send-count').textContent() === 'Composer sends: 1');
  check('Composer clears draft and retains normal focus', await page.getByTestId('lab-composer-current').inputValue() === '' && await page.getByTestId('lab-composer-current').evaluate(e => e === document.activeElement));
  await button('Pause').click();
  const paused = await timeline();
  await page.waitForTimeout(250);
  check('Pause freezes fixture time', await timeline() === paused);
  await seek(2100);
  const first = await snapshot();
  await button('Replay').click(); await button('Pause').click(); await seek(2100);
  check('Replay and seek project identical fixture content', JSON.stringify(await snapshot()) === JSON.stringify(first));
  await choose('Comparison', 'Side-by-side');
  check('Comparison has one shared clock across distinct renderers', await page.locator('[data-transcript]').evaluateAll(nodes => nodes.length === 2 && nodes[0].dataset.time === nodes[1].dataset.time));
  await seek(4200);
  await page.getByTestId('lab-composer-candidate').fill('A freely typed message');
  check('Comparison synchronizes the draft', await page.getByTestId('lab-composer-current').inputValue() === 'A freely typed message');
  await page.getByTestId('lab-composer-candidate').press('Shift+Enter');
  check('Shift+Enter keeps a multiline draft', (await page.getByTestId('lab-composer-current').inputValue()).includes('\n'));
  await page.getByTestId('lab-composer-candidate').press('Enter');
  check('Enter in candidate uses normal send flow', await page.getByTestId('send-count').textContent() === 'Composer sends: 3');
  await page.getByTestId('stop-button').first().click();
  check('Real composer Stop interrupts both renderers', await page.locator('[data-lifecycle="interrupted"]').count() === 2);
  await button('Recover response').first().click();
  await button('Pause').click();
  check('Recovery resumes shared fixture', await page.locator('[data-lifecycle="interrupted"]').count() === 0);
  await choose('Comparison', 'Current');
  await choose('Scenario', 'Attachment · failure → retry'); await seek(1900);
  check('Upload failure is visible', await page.locator('[data-item="upload"]').getAttribute('data-lifecycle') === 'failed');
  await button('Retry upload').click(); await button('Pause').click();
  check('Retry drives actual progress UI', await page.locator('[data-item="upload"]').getAttribute('data-lifecycle') === 'in-progress');
  await tab('States').click();
  check('States show only applicable attachment lifecycle snapshots', JSON.stringify(await page.locator('[data-snapshot] [data-item="upload"]').evaluateAll(es => es.map(e => e.dataset.lifecycle))) === JSON.stringify(['waiting', 'in-progress', 'complete', 'failed']));
  await button('Run scenario').click(); await button('Pause').click();
  check('Run from States opens conversation and sends', await tab('Conversation').getAttribute('data-state') === 'active' && await page.getByTestId('send-count').textContent() === 'Composer sends: 1');
  await choose('Scenario', 'Interrupted response → recovery'); await seek(2300);
  await button('Recover response').click(); await button('Pause').click();
  check('Scripted interruption recovers', await page.locator('[data-kind="response"]').getAttribute('data-lifecycle') === 'in-progress');
  await choose('Scenario', 'Thinking → tool → result → response'); await tab('Playback').click();
  await button('4.2s · tool · Complete').click();
  check('Playback event rail seeks tool result', (await page.locator('[data-item="search"]').textContent()).includes('3 notes found'));
  const directTool = await page.locator('[data-item="search"] [aria-expanded]').getAttribute('aria-expanded');
  await seek(2200); await seek(4200);
  check('Tool disclosure is deterministic across direct and sequential seeking', await page.locator('[data-item="search"] [aria-expanded]').getAttribute('aria-expanded') === directTool);
  await page.getByRole('slider', { name: 'Timeline', exact: true }).focus(); await page.keyboard.press('ArrowRight');
  check('Keyboard scrubber advances one step', (await timeline()).startsWith('4.3'));
  await choose('Playback speed', '4×'); await seek(0); await button('Play').click();
  await page.waitForTimeout(330); await button('Pause').click();
  check('Playback speed changes simulated rate', Number((await timeline()).split(' / ')[0]) >= 1.2);
  await page.getByRole('checkbox', { name: 'Reduced-motion preview' }).check();
  check('Reduced-motion preview reaches shared provider', await page.locator('.chat-ui-lab').getAttribute('data-caelos-reduced') === 'true');
  await choose('Playback speed', '1×');
  const presets = [
    ['Text response → complete', 4200], ['Thinking → tool → result → response', 7200],
    ['Artifact → preview → expanded document', 6000], ['Attachment · success', 4200],
    ['Attachment · failure → retry', 6500], ['Delegation → sub-agent → result', 6800],
    ['Interrupted response → recovery', 6600], ['Stress · speakers, long content & overlapping tools', 8500],
  ];
  for (const [name, end] of presets) {
    await choose('Scenario', name); await button('Run scenario').click(); await button('Pause').click(); await seek(end);
    check(`${name}: sends and completes`, await page.getByTestId('send-count').textContent() === 'Composer sends: 1' && await page.locator('[data-transcript] [data-item]').evaluateAll(es => es.length > 0 && es.every(e => e.dataset.lifecycle === 'complete')));
  }
  await tab('Conversation').click(); await seek(2500);
  check('Stress fixture overlaps tools with multiple speakers', await page.locator('[data-kind="tool"][data-lifecycle="in-progress"]').count() === 2 && await page.locator('[data-kind="delegation"]').count() === 1);
  await seek(8500);
  const viewport = page.getByRole('region', { name: 'current conversation messages', exact: true });
  await viewport.evaluate(e => { e.scrollTop = 0; }); await page.waitForTimeout(100);
  check('Scrolled-up transcript exposes jump action', await button('Jump to latest').isVisible());
  await button('Jump to latest').click();
  check('Jump to latest scrolls to bottom', await viewport.evaluate(e => e.scrollHeight - e.clientHeight - e.scrollTop < 2));
  const expand = button('Open expanded document');
  await expand.click();
  check('Expanded artifact uses actual shared dialog', await page.getByRole('dialog').isVisible());
  await page.keyboard.press('Tab'); await page.keyboard.press('Shift+Tab');
  check('Expanded artifact contains keyboard focus', await page.getByRole('dialog').evaluate(e => e.contains(document.activeElement)));
  const documentRegion = page.getByRole('region', { name: 'Expanded document contents' });
  check('Large document reader scrolls', await documentRegion.evaluate(e => e.scrollHeight > e.clientHeight));
  await page.screenshot({ path: `${evidence}expanded-document.png` });
  await page.keyboard.press('Escape');
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.waitForFunction(() => document.activeElement?.textContent === 'Open expanded document');
  check('Escape closes reader and restores trigger focus', await page.getByRole('dialog').count() === 0 && await expand.evaluate(e => e === document.activeElement));
  await choose('Comparison', 'Side-by-side');
  await button('1000px').click();
  await page.locator('.lab-workspace').screenshot({ path: `${evidence}comparison.png` });
  for (const size of [320, 390, 560]) {
    await button(`${size}px`).click();
    check(`${size}px surface fits without horizontal overflow`, await page.locator('.lab-stage').evaluate(e => e.scrollWidth <= e.clientWidth + 1));
    check(`${size}px comparison stacks`, await page.locator('.lab-chat').evaluateAll(es => es[1].getBoundingClientRect().top > es[0].getBoundingClientRect().top));
  }
  await choose('Comparison', 'Candidate');
  await button('Run scenario').click(); await button('Pause').click();
  check('Candidate-only scenario Run uses candidate composer', await page.getByTestId('lab-composer-candidate').count() === 1 && await page.getByTestId('lab-composer-current').count() === 0);
  await choose('Comparison', 'Current'); await button('1000px').click();
  await choose('Scenario', 'Tool permission → allow or deny'); await choose('Playback speed', '4×');
  await button('Run scenario').click(); await page.waitForTimeout(500);
  check('Permission stops the clock before the tool runs', (await timeline()).startsWith('1.0') && await button('Play').isDisabled() && await page.locator('[data-item="weather"]').count() === 0);
  await seek(4000);
  check('Scrubbing cannot bypass a pending decision', (await timeline()).startsWith('1.0') && await page.locator('[data-item="weather"]').count() === 0);
  await button('Review permission').click();
  await page.keyboard.press('Tab'); await page.keyboard.press('Shift+Tab');
  check('Permission popup contains keyboard focus', await page.getByRole('dialog').evaluate(e => e.contains(document.activeElement)));
  await page.screenshot({ path: `${evidence}permission-dialog.png` });
  await page.keyboard.press('Escape'); await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await page.waitForFunction(() => document.activeElement?.textContent === 'Review permission');
  check('Closing permission popup returns focus without deciding', await button('Review permission').evaluate(e => e === document.activeElement) && await page.getByTestId('recorded-decision').count() === 0);
  await button('Review permission').click(); await page.getByRole('dialog').getByRole('button', { name: 'Deny', exact: true }).click();
  await button('Pause').click(); await seek(4000);
  check('Deny skips tool execution and changes the response', (await page.locator('[data-item="weather"]').textContent()).includes('no tool was run') && (await page.locator('[data-kind="response"]').textContent()).includes('lookup was denied'));
  const deniedSnapshot = await snapshot();
  await button('Replay').click(); await page.waitForTimeout(400); await button('Pause').click();
  check('Replay retains the decision and passes its gate', Number((await timeline()).split(' / ')[0]) > 1 && (await page.getByTestId('recorded-decision').textContent()).includes('deny'));
  await seek(4000);
  check('Denied replay produces the identical branch', JSON.stringify(await snapshot()) === JSON.stringify(deniedSnapshot));
  await button('Run scenario').click(); await page.waitForTimeout(500);
  check('Fresh Run asks permission again', await button('Allow').isEnabled() && await page.getByTestId('recorded-decision').count() === 0);
  await choose('Comparison', 'Side-by-side'); await button('Allow').last().click(); await button('Pause').click(); await seek(1100);
  check('Allow in candidate starts the tool in both panes', await page.locator('[data-item="weather"][data-lifecycle="in-progress"]').count() === 2);
  await seek(4000);
  check('Permission comparison completes in sync', await page.locator('[data-transcript]').evaluateAll(es => es[0].querySelector('[data-kind="response"] .lab-copy')?.textContent === es[1].querySelector('[data-kind="response"] .lab-copy')?.textContent && es[0].dataset.time === es[1].dataset.time));
  await seek(1000);
  check('Seeking back cannot overwrite a recorded decision', await button('Deny').first().isDisabled() && await button('Allow').last().isDisabled());
  await choose('Scenario', 'User question → choice or text answer'); await seek(4000);
  check('User question pauses for a nonempty answer', (await timeline()).startsWith('1.0') && await button('Submit answer').first().isDisabled());
  await button('Document reading').last().click();
  check('Question choice fills synchronized text fields without submitting', JSON.stringify(await page.getByRole('textbox', { name: 'Your answer', exact: true }).evaluateAll(es => es.map(e => e.value))) === JSON.stringify(['Document reading', 'Document reading']) && await page.getByTestId('recorded-decision').count() === 0);
  await page.getByRole('textbox', { name: 'Your answer', exact: true }).first().fill('   ');
  check('Whitespace answer cannot submit', await button('Submit answer').first().isDisabled());
  await page.getByRole('textbox', { name: 'Your answer', exact: true }).last().fill('Keyboard navigation and long documents');
  await button('Submit answer').last().focus(); await page.keyboard.press('Enter'); await button('Pause').click(); await seek(4000);
  check('Keyboard submission records free text and drives both responses', await page.locator('[data-kind="response"]').evaluateAll(es => es.length === 2 && es.every(e => e.textContent.includes('Keyboard navigation and long documents'))));
  await button('Replay').click(); await button('Pause').click(); await seek(4000);
  check('Question replay retains its answer', (await page.getByTestId('recorded-decision').textContent()).includes('Keyboard navigation and long documents'));
  await button('Run scenario').click(); await page.waitForTimeout(500);
  await button('Skip question').first().click(); await button('Pause').click(); await seek(4000);
  check('Skipping a question resumes with explicit default behavior', (await page.locator('[data-kind="response"]').first().textContent()).includes('Question skipped'));
  await button('Run scenario').click(); await page.waitForTimeout(500); await button('320px').click();
  check('Question controls fit a narrow surface', await page.locator('.lab-chat').evaluateAll(es => es.every(e => e.scrollWidth <= e.clientWidth + 1)));
  await page.locator('.lab-stage').screenshot({ path: `${evidence}narrow-question.png` });
  await choose('Scenario', 'Unread messages → return to latest'); await button('1000px').click(); await choose('Playback speed', '0.5×');
  await button('Run scenario').click();
  await button('1 new message · Jump to latest').first().waitFor({ state: 'visible' }); await button('Pause').click();
  check('Timed arrival announces an unread message while reading earlier content', await page.getByRole('separator', { name: '1 unread message', exact: true }).count() === 2 && await page.getByRole('region', { name: 'current conversation messages', exact: true }).evaluate(e => e.scrollTop === 0));
  await button('Play').click();
  await button('3 new messages · Jump to latest').first().waitFor({ state: 'visible' }); await button('Pause').click();
  check('Subsequent timed arrivals accumulate without moving the reader', await page.getByRole('separator', { name: '3 unread messages', exact: true }).count() === 2 && await page.getByRole('region', { name: 'current conversation messages', exact: true }).evaluate(e => e.scrollTop === 0));
  for (const [at, count] of [[1600, 1], [3000, 2], [4400, 3]]) {
    await seek(at); await page.waitForTimeout(100);
    check(`${count} unread arrivals place the marker at the first unread message`, await page.getByRole('separator', { name: `${count} unread ${count === 1 ? 'message' : 'messages'}`, exact: true }).count() === 2 && await page.locator('[data-unread-divider]').evaluateAll(es => es.every(e => e.nextElementSibling?.dataset.item === 'unread-a')));
  }
  check('New arrivals preserve earlier reading position', await page.getByRole('region', { name: 'current conversation messages', exact: true }).evaluate(e => e.scrollTop === 0 && e.scrollHeight > e.clientHeight));
  await page.locator('[data-unread-divider]').first().evaluate(e => e.scrollIntoView({ block: 'center' }));
  await page.locator('.lab-workspace').screenshot({ path: `${evidence}unread-comparison.png` });
  await button('3 new messages · Jump to latest').last().click();
  check('Jump clears synchronized unread markers and restores viewport focus', await page.locator('[data-unread-divider]').count() === 0 && await page.getByRole('region', { name: 'candidate conversation messages', exact: true }).evaluate(e => e === document.activeElement && e.scrollHeight - e.scrollTop - e.clientHeight < 2));
  await seek(3000); await page.waitForTimeout(100);
  check('Seeking restores the deterministic unread boundary', await page.locator('[data-unread-divider]').count() === 2);
  await page.getByRole('region', { name: 'current conversation messages', exact: true }).evaluate(e => { e.scrollTop = e.scrollHeight; }); await page.waitForTimeout(150);
  check('Manual scrolling to the bottom marks messages read', await page.locator('[data-unread-divider]').count() === 0);
  await tab('States').click();
  check('Unread States include clear, single and multiple arrivals', await page.getByText('All messages read · no divider', { exact: true }).isVisible() && await page.getByRole('separator', { name: '1 unread message', exact: true }).count() === 1 && await page.getByRole('separator', { name: '3 unread messages', exact: true }).count() === 1);
  await tab('Conversation').click(); await seek(4400); await button('320px').click();
  check('Unread controls fit narrow surfaces', await page.locator('.lab-chat').evaluateAll(es => es.every(e => e.scrollWidth <= e.clientWidth + 1)));
  await button('Reset lab').click();
  check('Reset removes unread and decision data', await page.locator('[data-unread-divider]').count() === 0 && await page.getByTestId('recorded-decision').count() === 0);
  await choose('Comparison', 'Candidate'); await choose('Playback speed', '1×');
  await choose('Scenario', 'Empty conversation'); await button('Run scenario').click();
  check('Empty fixture remains empty after normal send', await page.locator('[data-item]').count() === 0 && await page.getByTestId('send-count').textContent() === 'Composer sends: 1');
  await button('Reset lab').click();
  check('Reset clears lab sends and draft', await page.getByTestId('send-count').textContent() === 'Composer sends: 0' && await page.getByTestId('lab-composer-candidate').inputValue() === '');
  check('Reset leaves storage unchanged', JSON.stringify(await page.evaluate(() => [JSON.stringify(localStorage), JSON.stringify(sessionStorage)])) === JSON.stringify(originalStorage));
  await choose('Scenario', 'Text response → complete');
  await choose('Comparison', 'Current');
  await button('Add to this conversation').click();
  await page.getByRole('menuitem', { name: 'File or folder', exact: true }).click();
  check('Composer Add attaches local fixture metadata', await button('Remove attachment').isVisible());
  await button('Add to this conversation').click();
  await page.getByRole('menuitem', { name: 'Goal', exact: true }).click();
  await page.getByRole('textbox', { name: 'Goal', exact: true }).fill('Review the lab');
  await button('Save').click();
  await button('Model and reasoning: Fixture model, Standard').focus(); await page.keyboard.press('ArrowDown');
  await button('Model: Fixture model').click();
  await page.getByRole('menuitemradio', { name: 'Fixture model B', exact: true }).click();
  await button('Reasoning: Standard').click();
  await page.getByRole('menuitemradio', { name: 'Extended', exact: true }).click();
  await page.keyboard.press('Escape');
  await button('Reply format: Text').click();
  await page.getByRole('menuitemradio', { name: 'Text + voice', exact: true }).click();
  await button('Dictate a message').click();
  check('Dictation uses a labeled local simulation', (await page.getByTestId('lab-notice').textContent()).includes('No microphone was accessed'));
  await page.getByTestId('lab-composer-current').press('Enter'); await button('Pause').click();
  await page.getByText('Last composer payload', { exact: true }).click();
  const payload = JSON.parse(await page.locator('.lab-payload').textContent());
  check('Normal composer settings reach send payload', payload.model === 'Fixture model B' && payload.reasoning === 'Extended' && payload.replyFormat === 'both' && payload.goal === 'Review the lab');
  await choose('Scenario', 'Stress · speakers, long content & overlapping tools');
  await seek(2500); await button('320px').click();
  await page.locator('.lab-chat').screenshot({ path: `${evidence}narrow-stress.png` });
  await tab('States').click();
  await page.locator('.lab-workspace').screenshot({ path: `${evidence}states.png` });
  await tab('Conversation').click();
  await seek(8500); await page.setViewportSize({ width: 390, height: 844 });
  await button('Open expanded document').click();
  check('Narrow expanded artifact fits viewport', await page.getByRole('dialog').evaluate(e => e.getBoundingClientRect().left >= 0 && e.getBoundingClientRect().right <= innerWidth && e.getBoundingClientRect().bottom <= innerHeight));
  await page.keyboard.press('Escape'); await page.getByRole('dialog').waitFor({ state: 'hidden' });
  await choose('Scenario', 'Empty conversation');
  await choose('Lab theme', 'Light'); await page.setViewportSize({ width: 390, height: 844 });
  await page.locator('.lab-chat').screenshot({ path: `${evidence}narrow-light.png` });
  check('390px page has no horizontal overflow', await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth));
  await tab('Approved spacing').click();
  check('Spacing reference draft survives lab/reset/tab navigation', await page.getByRole('textbox', { name: 'Project name', exact: true }).inputValue() === 'Preserved spacing draft');
  check('Default density remains selected', await button('Default').getAttribute('aria-pressed') === 'true');
  check('No browser runtime errors', errors.length === 0);
  check('Only local static GET requests; no API or AI traffic', requests.every(r => r.url.startsWith(base) && r.method === 'GET' && !['fetch', 'xhr', 'websocket'].includes(r.type)));
  await writeFile(`${evidence}verification.json`, JSON.stringify({ url: base, passed, errors, requests }, null, 2));
  console.log(`${passed.length} checks passed. Evidence: ${evidence}`);
} catch (error) {
  await page.screenshot({ path: `${evidence}failure.png`, fullPage: true });
  console.error('Focus at failure:', await page.evaluate(() => document.activeElement?.outerHTML.slice(0,400)));
  throw error;
} finally { await browser.close(); }
