export const studies = [
  { id: 'activity', title: 'One activity language', brief: 'Waiting, thinking, tools, steps and delegation share one borderless disclosure. A single move stays a row; several moves become a collapsed chain.', decision: 'Count first with a visible current step: compare the history connector.', a: 'Count first', aNote: 'Leading-dot summary with status indicators beside each action label. Current action remains beneath the count; open to see the indented history.', b: 'Inset history rail', bNote: 'Same count and current step, with a continuous inset rail.', states: ['Single thought', 'Tool call', 'Two steps', 'Connected chain', 'Delegation'], start: 'Connected chain' },
  { id: 'messages', title: 'Identity & text arrival', brief: 'Open conversation space, no avatar card. Names appear only when several agents are participating. The activity history remains accessible.', decision: 'Inline names are carried forward. Compare phrase and paragraph arrival.', a: 'Inline name · phrases', aNote: 'The name leads the first line; incoming phrases soften in together.', b: 'Inline name · paragraphs', bNote: 'The same larger inline name; whole paragraphs arrive.', states: ['Multiple agents', 'Single agent'], start: 'Multiple agents' },
  { id: 'material', title: 'Message & code surfaces', brief: 'Compare the stronger composer material with the previous bubble diffusion. Code sits on a plain reading plane inside glass, never on a patch of ground.', decision: 'Which material relationship gives enough separation without making the conversation heavy?', a: 'Composer fill · raised code', aNote: 'Composer fill with focused diffusion; glass code shell with a plain higher plane.', b: 'Previous diffusion · raised code', bNote: 'Previous bubble diffusion for comparison. Code uses the accepted higher plain inner plane.', states: ['User message', 'Code block'], start: 'User message' },
  { id: 'preview', title: 'One preview family', brief: 'Documents, web pages and delegated work share an unboxed title trigger and an optional glass preview. Expand opens their reading workspace.', decision: 'All glass was chosen from mock-ups on September 20. Compare it live with strip and paper before locking.', a: 'All glass', aNote: 'One glass card. A darker strip carries type, name and actions and melts into the excerpt. No divider, no nested card.', b: 'Strip and paper', bNote: 'Same glass card and strip. The excerpt sits on a plain paper plane that runs the full width of the card: no glass overhang, no side border.', states: ['Artifact', 'Web page', 'Agent session'], start: 'Artifact' },
  { id: 'workspace', title: 'Expanded workspace', brief: 'Glass chrome around a plain higher document plane. Tools sit at the document’s upper-left edge, with collapse, panel-close and full-screen controls.', decision: 'All glass was chosen from mock-ups on September 20. Compare it live with strip and paper before locking.', a: 'All glass', aNote: 'One glass card on the conversation’s own ground: chrome strip melting into a glass document. No second graph-paper layer; the side panel no longer dims the chat.', b: 'Strip and paper', bNote: 'Same glass card and strip. The document sits on a plain paper plane that runs the full width and to the bottom of the card: no glass overhang, no side border.', states: ['Document', 'Agent session'], start: 'Document' },
  { id: 'permission', title: 'Permission at the composer', brief: 'A plain-English request, its reason, and the relevant command. Clarify focuses the existing composer with “clarifying question:”; Send submits. Allow, deny and clarification update only the local fixture.', decision: 'Compare plain and glass raised cards, both aligned to the composer.', a: 'Plain request card', aNote: 'A complete raised surface with inset text and actions.', b: 'Glass request card', bNote: 'The same card geometry with the glass surface material.', states: ['Permission required'], start: 'Permission required' },
  { id: 'questions', title: 'Questions with the composer', brief: 'Question progress and previous/next controls stay on the card. Choice clicks answer immediately. Other focuses the existing composer with “other answer:”; Send submits. The previous chat draft is restored.', decision: 'Full choice rows are carried forward; both fixtures support immediate answers and custom answers through the existing composer.', a: 'Choice rows', aNote: 'Long answers remain easy to scan and select.', b: 'Choice rows · same flow', bNote: 'A second fixture for comparing custom-answer and direct-selection flows.', states: ['Two questions'], start: 'Two questions' },
  { id: 'attachment', title: 'Files, upload & retry', brief: 'A rectangular file item with a type icon and complete filename. Failure uses the semantic danger tint, line, glow and tokenized retry.', decision: 'Put supporting file details on a second line, or beside the filename?', a: 'Two-line file card', aNote: 'Name first, type and size below. Comfortable with long filenames.', b: 'Compact file row', bNote: 'Metadata sits alongside the name when space permits.', states: ['Ready', 'Uploading', 'Failed'], start: 'Ready' },
  { id: 'sources', title: 'Inline sources', brief: 'A small descriptive citation within the sentence. Hover or focus reveals the title and complete URL, without a large hover card.', decision: 'Should the citation read as a pill or as a lightly underlined reference?', a: 'Quiet chip', aNote: 'A small fill makes the interactive boundary easy to find.', b: 'Text reference', bNote: 'An underline preserves the continuity of the sentence.', states: ['One source', 'Several sources'], start: 'One source' },
  { id: 'recovery', title: 'Orientation & recovery', brief: 'A light unread boundary, a jump-to-latest control, and a compact error with a retry icon. No permanent status badge on responses.', decision: 'Keep recovery and navigation icon-led, or include short contextual text?', a: 'Icon-led', aNote: 'Tooltips explain the control; the conversation stays quiet.', b: 'With context', bNote: 'A few words make unread counts and retry intent explicit.', states: ['Unread', 'Working below', 'Finished below', 'Interrupted', 'Error'], start: 'Error' },
] as const;
export type Study = Omit<typeof studies[number], 'title' | 'brief' | 'decision' | 'a' | 'aNote' | 'b' | 'bNote' | 'states' | 'start'> & { title: string; brief: string; decision: string; a: string; aNote: string; b: string; bNote: string; states: readonly string[]; start: string };
export type Variant = 'a' | 'b';
export type Phase = 'waiting' | 'working' | 'complete';
