export type Study = {
  id: string; title: string; description: string; source?: string;
  states: string[]; candidate?: { scenario: string; kind?: string };
  gap?: string; height?: number;
};
export const studies: Study[] = [
  { id: 'identity', title: 'Agent identity & continuation', description: 'Quiet name, avatar, and indented content. Inspect speaker changes and consecutive messages without redesigning avatar geometry.', source: 'components/chat/message.tsx → AgentMessage', states: ['complete', 'continuation', 'multiple agents'], candidate: { scenario: 'text' } },
  { id: 'user', title: 'User messages', description: 'Actual message surface, wrapping, and edit/copy affordances.', source: 'components/chat/message.tsx', states: ['complete', 'long text'] },
  { id: 'assistant', title: 'Assistant text & appearance motion', description: 'Completed and streaming text. Replay uses fixture chunks; it does not model provider latency.', source: 'components/chat/message.tsx → MessageResponse', states: ['complete', 'streaming'], candidate: { scenario: 'text' } },
  { id: 'markdown', title: 'Markdown & code', description: 'Headings, paragraphs, lists, tables, fenced code, and horizontal overflow in the actual message renderer.', source: 'components/chat/message.tsx → components/ai-elements/message.tsx', states: ['complete'], height: 620 },
  { id: 'waiting', title: 'Waiting & loading', description: 'The initial waiting indicator and an empty assistant response waiting for content.', source: 'components/chat/message.tsx → ThinkingMessage / PreviewMessage', states: ['initial wait', 'response wait'], candidate: { scenario: 'tools', kind: 'thinking' } },
  { id: 'reasoning', title: 'Thinking disclosure', description: 'The actual rounded disclosure, streaming summary, and expandable reasoning content.', source: 'components/chat/message-reasoning.tsx → components/ai-elements/reasoning.tsx', states: ['complete', 'streaming'], candidate: { scenario: 'tools', kind: 'thinking' } },
  { id: 'tool', title: 'Tool calls & results', description: 'Actual getWeather branch: call, result, failure, and denied state. Other tools are not interchangeable with this implementation.', source: 'components/chat/message.tsx → tool-getWeather / Weather', states: ['running', 'complete', 'failed', 'denied'], candidate: { scenario: 'tools', kind: 'tool' }, height: 520, gap: 'No generic catch-all tool renderer is wired into PreviewMessage; unknown tool parts return no UI.' },
  { id: 'permission', title: 'Tool permissions', description: 'Actual inline Allow / Deny actions. Decisions update only this fixture.', source: 'components/chat/message.tsx → ToolApprovalActions', states: ['awaiting decision', 'allowed', 'denied'], candidate: { scenario: 'approval', kind: 'approval' } },
  { id: 'question', title: 'Questions & questionnaires', description: 'Choice, free-text, and multi-question experiments.', states: ['waiting', 'complete'], candidate: { scenario: 'questionnaire', kind: 'question' }, gap: 'No structured questionnaire branch found in the staging message assembly. The right-hand specimen is a local experiment.' },
  { id: 'attachment', title: 'Attachments & uploads', description: 'Actual upload overlay, completed attachment, and removal control.', source: 'components/chat/preview-attachment.tsx', states: ['complete', 'uploading'], candidate: { scenario: 'upload-success', kind: 'attachment' } },
  { id: 'upload-retry', title: 'Upload failure & retry', description: 'Inspect the existing retry experiment independently.', states: ['failed', 'complete'], candidate: { scenario: 'upload-retry', kind: 'attachment' }, gap: 'Staging reports upload failures through a toast in MultimodalInput; no discrete retry card is wired there.' },
  { id: 'inline-artifact', title: 'Inline artifact', description: 'Actual 450px document preview: title, rich text, fade, loading skeleton, and open control.', source: 'components/chat/document-preview.tsx', states: ['complete', 'generating'], candidate: { scenario: 'artifact', kind: 'artifact' }, height: 630 },
  { id: 'expanded-artifact', title: 'Expanded artifact workspace', description: 'Actual reading/editing plane, title, close, version navigation, copy, and suggestion actions. Open the full-size specimen to inspect the desktop side panel.', source: 'components/chat/artifact.tsx', states: ['complete', 'generating'], height: 720 },
  { id: 'actions', title: 'Message actions', description: 'Actual assistant copy/vote and user edit/copy actions; votes are memory-only. Hover or focus inside the specimen.', source: 'components/chat/message-actions.tsx via PreviewMessage', states: ['assistant', 'user'] },
  { id: 'citations', title: 'Citations & sources', description: 'Citation inspection and source popover experiment.', states: ['complete'], candidate: { scenario: 'citations', kind: 'response' }, gap: 'Citation primitives exist, but no source-part rendering is wired into PreviewMessage. Ordinary markdown links are not a structured citation system.' },
  { id: 'web-preview', title: 'Web preview', description: 'Local interactive page preview experiment.', states: ['complete'], candidate: { scenario: 'web-preview', kind: 'artifact' }, gap: 'No dedicated website-preview artifact is registered in staging. Registered kinds are text, code, image, and sheet.', height: 620 },
  { id: 'progress', title: 'Steps & work progress', description: 'Grouped work-step experiment; retain honest distinction from individual staging tool branches.', states: ['in-progress', 'complete'], candidate: { scenario: 'tools', kind: 'tool' }, gap: 'No unified work-step component is wired into the staging message assembly.' },
  { id: 'delegation', title: 'Delegation & sub-agents', description: 'Delegated task and agent activity experiment.', states: ['waiting', 'in-progress', 'complete'], candidate: { scenario: 'delegation', kind: 'delegation' }, gap: 'Agent identities exist; a dedicated sub-agent execution indicator is not wired into PreviewMessage.' },
  { id: 'navigation', title: 'Conversation navigation', description: 'Actual scroll container and jump-to-latest control. Scroll upward inside the frame to inspect it.', source: 'components/chat/messages.tsx → useMessages', states: ['long conversation'], height: 580 },
  { id: 'unread', title: 'Unread boundary', description: 'Unread-divider experiment; full follow/return behavior remains available in Demo.', states: ['new messages'], candidate: { scenario: 'unread' }, gap: 'Staging has jump-to-latest, but no unread divider/count is wired into Messages.' },
  { id: 'recovery', title: 'Interruption & recovery', description: 'Interrupted-response experiment. Tool failure is also inspectable in Tool calls & results.', states: ['interrupted', 'complete'], candidate: { scenario: 'interrupted', kind: 'response' }, gap: 'No standalone interrupted-response recovery card is wired into PreviewMessage; chat-level errors and stop behavior are separate flows.' },
  { id: 'empty', title: 'Empty conversation', description: 'Actual empty-conversation greeting.', source: 'components/chat/greeting.tsx', states: ['empty'] },
  { id: 'composer', title: 'Composer · locked reference', description: 'Unmodified staging composer, with isolated context and submission callbacks. Its controls remain available as a reference; it is not a redesign target.', source: 'components/chat/multimodal-input.tsx → shared Composer', states: ['ready'], height: 560 },
];
