import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
const out='/private/tmp/caelos-composer-context';
await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:950}});
page.setDefaultTimeout(10000);
const errors=[];
page.on('pageerror',e=>errors.push(e.message));
const goal='Ship a calm, accessible composer.\nKeep the conversation focused on the release.';
const instruction='Use concise explanations and ask before making irreversible changes.';
try {
 await page.goto(process.env.PREVIEW_URL || 'http://127.0.0.1:3101/ui-lab');
 const primary=page.locator('[data-composer-demo=primary]');
 const field=primary.getByRole('textbox',{name:'Message',exact:true});
 await field.fill('My draft stays here.');
 const add=async kind=>{
  await primary.getByRole('button',{name:'Add to this conversation'}).click();
  await page.getByRole('menuitem',{name:kind,exact:true}).click();
  await page.getByRole('dialog').waitFor();
  await page.waitForTimeout(350);
  assert.ok(await page.getByRole('dialog').getByRole('textbox').evaluate(el=>el===document.activeElement),'editor keeps focus after the add menu closes');
 };
 await add('Goal');
 const editor=page.getByRole('dialog');
 assert.equal(await editor.getByRole('button',{name:'Save',exact:true}).isEnabled(),false);
 await editor.getByRole('textbox',{name:'Goal',exact:true}).fill(goal);
 await editor.getByRole('button',{name:'Save',exact:true}).click();
 await editor.waitFor({state:'hidden'});
 assert.equal(await field.inputValue(),'My draft stays here.');
 const pill=primary.getByRole('button',{name:'Edit goal',exact:true});
 await pill.hover();
 await page.getByRole('tooltip',{name:/Ship a calm, accessible composer/}).waitFor();
 assert.equal(await page.getByRole('tooltip',{name:/Ship a calm, accessible composer/}).textContent(),goal);
 await primary.locator('.nc-composer-workspace').screenshot({path:`${out}/goal-hover.png`});
 await pill.click();
 assert.equal(await editor.getByRole('textbox').inputValue(),goal);
 await editor.getByRole('textbox').fill('An unsaved edit');
 await page.keyboard.press('Escape');
 await editor.waitFor({state:'hidden'});
 await pill.focus();
 await page.getByRole('tooltip',{name:/Ship a calm, accessible composer/}).waitFor();
 assert.equal(await page.getByRole('tooltip',{name:/Ship a calm, accessible composer/}).textContent(),goal);
 await pill.click();
 await field.click();
 await editor.waitFor({state:'hidden'});
 assert.ok(await field.evaluate(el=>el===document.activeElement),'outside dismissal preserves the clicked field focus');
 await pill.click();
 await editor.getByRole('textbox').fill(goal+' Edited.');
 await editor.getByRole('button',{name:'Save',exact:true}).click();
 await editor.waitFor({state:'hidden'});
 await add('Session instruction');
 await editor.getByRole('textbox').fill(instruction);
 await editor.getByRole('button',{name:'Save',exact:true}).click();
 await editor.waitFor({state:'hidden'});
 assert.equal(await primary.locator('.nc-composer-pill').count(),2);
 assert.equal(await page.locator('[data-composer-demo=secondary] .nc-composer-pill').count(),0);
 assert.equal(await pill.locator('svg').getAttribute('class'),'lucide lucide-goal');
 await primary.getByRole('button',{name:'Add to this conversation'}).click();
 assert.equal(await page.getByRole('menuitem',{name:'Goal',exact:true}).locator('svg').getAttribute('class'),'lucide lucide-goal');
 await page.keyboard.press('Escape');
 await primary.screenshot({path:`${out}/desktop.png`});
 await primary.getByRole('button',{name:'Send message',exact:true}).click();
 assert.equal(await field.inputValue(),'');
 assert.equal(await primary.locator('.nc-composer-pill').count(),2);
 for(const width of [353,390]) {
  await page.setViewportSize({width,height:900});
  await primary.scrollIntoViewIfNeeded();
  const bounds=await primary.evaluate(root=>{
   const shell=root.querySelector('.nc-composer-shell').getBoundingClientRect();
   return [...root.querySelectorAll('.nc-composer-pill,.nc-composer-controls button')].filter(el=>el.checkVisibility({opacityProperty:true,visibilityProperty:true})).filter(el=>{const r=el.getBoundingClientRect();return !(r.x>=shell.x && r.right<=shell.right && r.bottom<=shell.bottom)}).map(el=>({label:el.getAttribute('aria-label'),rect:el.getBoundingClientRect().toJSON(),shell:shell.toJSON()}));
  });
  await primary.screenshot({path:`${out}/narrow-${width}.png`});
  assert.deepEqual(bounds,[],'pills and controls fit inside composer');
 }
 await page.getByRole('button',{name:'Switch to light',exact:true}).click();
 await pill.click();
 await editor.waitFor();
 assert.equal(await editor.getAttribute('data-caelos-theme'),'light');
 await page.screenshot({path:`${out}/light-editor.png`});
 await editor.getByRole('button',{name:'Cancel',exact:true}).click();
 await primary.getByRole('button',{name:'Remove goal',exact:true}).click();
 assert.equal(await primary.getByRole('button',{name:'Edit goal',exact:true}).count(),0);
 assert.equal(await primary.getByRole('button',{name:'Edit instruction',exact:true}).count(),1);
 await primary.getByRole('button',{name:'Remove instruction',exact:true}).click();
 assert.equal(await primary.locator('.nc-composer-pill').count(),0);
 const touch=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});
 await touch.goto(process.env.PREVIEW_URL || 'http://127.0.0.1:3101/ui-lab');
 const touchComposer=touch.locator('[data-composer-demo=primary]');
 await touchComposer.getByRole('button',{name:'Add to this conversation'}).tap();
 await touch.getByRole('menuitem',{name:'Goal',exact:true}).tap();
 await touch.getByRole('dialog').getByRole('textbox').fill(goal);
 await touch.getByRole('button',{name:'Save',exact:true}).tap();
 await touchComposer.getByRole('button',{name:'Edit goal',exact:true}).tap();
 assert.equal(await touch.getByRole('dialog').getByRole('textbox').inputValue(),goal);
 await touch.close();
 assert.deepEqual(errors,[]);
 console.log('PASS add/edit/save/cancel/remove, exact hover/focus text, outside focus, touch editing, independent instances, draft and send persistence, default Goal icon in pill and menu, narrow layouts, light editor; zero page errors');
} finally {await browser.close();}
