import React, {useState, useRef, useEffect} from 'react';
import {GripHorizontal, Layers, ArrowUpRight, RotateCcw, Pin, Copy, Check} from 'lucide-react';

export const MATERIAL_PRESETS = {dark:{transparency:76,blur:19,tint:14,hue:'Violet'},light:{transparency:24,blur:2,tint:23,hue:'Violet'}};
export const DEFAULT_MATERIAL = MATERIAL_PRESETS.dark;
export function MaterialControls({material,setMaterial,materialMode,setMaterialMode,opaque,setOpaque,reduced,setReduce,systemReduced}) {
 return <div className="material-controls independent-controls"><div className="material-mode-row"><div className="material-modes" role="group" aria-label="Material mode"><span>Material mode</span>{['dark','light'].map(mode=><button key={mode} aria-pressed={materialMode===mode} onClick={()=>setMaterialMode(mode)}>{mode==='dark'?'Dark':'Light'}</button>)}</div><span>Panels & menus · separate presets</span></div><div className="material-sliders">{[['transparency','Transparency',0,100,'%'],['blur','Background blur',0,48,'px'],['tint','Tint strength',0,30,'%']].map(([key,label,min,max,unit])=><label className="material-slider" key={key}><span>{label}<output>{material[key]}{unit}</output></span><input type="range" min={min} max={max} value={material[key]} disabled={opaque} aria-label={label} onChange={e=>setMaterial(v=>({...v,[key]:+e.target.value}))}/></label>)}</div><div className="material-options"><label>Tint <select aria-label="Glass tint color" value={material.hue} disabled={opaque} onChange={e=>setMaterial(v=>({...v,hue:e.target.value}))}>{['Violet','Sage','Neutral'].map(h=><option key={h}>{h}</option>)}</select></label><span className="material-control-hint">Independent controls · text stays opaque</span><button className="text-button compact" onClick={()=>{setMaterial(MATERIAL_PRESETS[materialMode]);setOpaque(false)}}><RotateCcw size={12}/>Reset material</button><button className="control-switch" aria-pressed={opaque} onClick={()=>setOpaque(!opaque)}>Opaque</button><button className="control-switch" aria-pressed={!!reduced} disabled={!!systemReduced} title={systemReduced?'Enabled by your system preference':undefined} onClick={()=>setReduce(!reduced)}>Reduced motion</button></div></div>
}
const BACKGROUNDS=['Graph paper','Workspace','Light & shade'];
export function MaterialLab({mode='panel',notify}) {
 const [background,setBackground]=useState('Graph paper');const [position,setPosition]=useState({x:42,y:65});const [dragging,setDragging]=useState(false);const [pinned,setPinned]=useState(false);
 const stage=useRef(null),panel=useRef(null),drag=useRef(null);const prefix=mode==='menu'?'menu':'panel';
 const constrain=(p)=>{if(!stage.current||!panel.current)return p;return {x:Math.max(12,Math.min(p.x,stage.current.clientWidth-panel.current.offsetWidth-12)),y:Math.max(12,Math.min(p.y,stage.current.clientHeight-panel.current.offsetHeight-12))}};
 useEffect(()=>{const observer=new ResizeObserver(()=>setPosition(p=>constrain(p)));observer.observe(stage.current);observer.observe(panel.current);return ()=>observer.disconnect()},[]);
 const endDrag=e=>{drag.current=null;setDragging(false);if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId)};
 return <div className="material-lab"><div className="lab-toolbar"><div className="lab-backgrounds" role="group" aria-label={`${prefix} backdrop`}>{BACKGROUNDS.map(b=><button key={b} aria-pressed={background===b} onClick={()=>setBackground(b)}>{b}</button>)}</div><button className="text-button compact" onClick={()=>setPosition(constrain({x:42,y:65}))}><RotateCcw size={12}/>Reset position</button></div><div ref={stage} className={`lab-stage lab-${background==='Graph paper'?'grid':background==='Workspace'?'workspace':'split'}`}>
 <div className="lab-background-content" aria-hidden="true">{background==='Graph paper'?<><span className="lab-coordinate">CAE / MATERIAL STUDY</span><h4>Clarity has depth.</h4><p>Move across the grid.<br/>Observe what stays visible.</p><span className="lab-grid-note">04 — 08 — 12 — 16</span></>:background==='Workspace'?<><div className="lab-project-heading">Core platform <span>September cycle</span></div>{['Refine the material system','Unify the input family','Review project milestones','Ship the next foundation','Collect the small details'].map((t,i)=><div className="lab-background-task" key={t}><span className={`dot ${i%2?'ready':'progress'}`}/><span>{t}</span><small>{i%2?'Ready':'In progress'}</small></div>)}</>:<><div className="light-field"><h4>Light</h4><p>A more demanding reading surface.</p></div><div className="dark-field"><h4>Shade</h4><p>The same material, a different setting.</p></div></>}</div>
 <div ref={panel} className={`lab-floating glass ${mode==='menu'?'lab-menu':'lab-panel'} ${dragging?'is-dragging':''}`} style={{left:position.x,top:position.y}}><button className="lab-drag-handle" aria-label={`Move glass ${prefix}`} aria-describedby={`${prefix}-drag-help`} onPointerDown={e=>{if(e.button!==0)return;drag.current={x:e.clientX,y:e.clientY,origin:position};setDragging(true);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!drag.current)return;setPosition(constrain({x:drag.current.origin.x+e.clientX-drag.current.x,y:drag.current.origin.y+e.clientY-drag.current.y}))}} onPointerUp={endDrag} onPointerCancel={endDrag} onKeyDown={e=>{const delta={ArrowLeft:[-1,0],ArrowRight:[1,0],ArrowUp:[0,-1],ArrowDown:[0,1]}[e.key];if(delta){e.preventDefault();const step=e.shiftKey?40:10;setPosition(p=>constrain({x:p.x+delta[0]*step,y:p.y+delta[1]*step}))}}}><GripHorizontal size={19}/><span>Drag to explore</span></button>
 {mode==='panel'?<div className="lab-panel-content"><div className="project-top"><span className="project-icon"><Layers size={18}/></span><button className="icon-button" aria-label="Inspect material project" onClick={()=>notify('Material study · three independent controls, one opaque text layer.')}><ArrowUpRight size={16}/></button></div><h4>Core platform</h4><p>Space for clear thinking.<br/>Depth that supports the work.</p><div className="project-foot"><span className="status progress">In progress</span><span className="lab-owner">Daniel</span></div></div>:<div className="lab-menu-content"><div className="menu-context"><span className="project-icon"><Layers size={16}/></span><div>Core platform<small>Project workspace</small></div></div><button className="menu-item" onClick={()=>notify('Core platform · 8 milestones, 3 collaborators.')}><span><ArrowUpRight size={15}/>Open project</span></button><button className="menu-item" onClick={()=>{setPinned(!pinned);notify(pinned?'Project unpinned in material study.':'Project pinned in material study.')}}><span><Pin size={15}/>{pinned?'Unpin from sidebar':'Pin to sidebar'}</span>{pinned&&<Check size={14}/>}</button><button className="menu-item" onClick={()=>notify('Project reference: CAE-208 · Core platform.')}><span><Copy size={15}/>View project reference</span></button><div className="menu-foot">A menu surface over real content</div></div>}
 </div></div><div className="lab-caption"><p id={`${prefix}-drag-help`}>Drag the handle, or focus it and use arrow keys. Shift moves farther.</p><span>Background stays fixed</span></div></div>
}
