import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import fs from 'node:fs/promises';
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1280,height:1000}});page.setDefaultTimeout(10000);
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto(process.env.PREVIEW_URL || 'http://127.0.0.1:5186');
const sample=page.getByRole('region',{name:'Shared foundations'});
await sample.scrollIntoViewIfNeeded();
const range=sample.getByRole('slider',{name:'Completion'});
await range.focus();await range.press('ArrowRight');assert.equal(await range.inputValue(),'40');
assert.equal(await sample.getByRole('progressbar').getAttribute('value'),'40');
const checkbox=sample.getByRole('checkbox',{name:'Include completed items'});await checkbox.focus();await checkbox.press('Space');assert(await checkbox.isChecked());
const handle=sample.getByRole('separator',{name:'Sample pane width'});
await handle.focus();await handle.press('End');assert.equal(await handle.getAttribute('aria-valuenow'),'320');
await handle.press('Home');assert.equal(await handle.getAttribute('aria-valuenow'),'120');await handle.press('ArrowRight');assert.equal(await handle.getAttribute('aria-valuenow'),'128');
const box=await handle.boundingBox();await page.mouse.move(box.x+4,box.y+10);await page.mouse.down();await page.mouse.move(box.x+104,box.y+10);await page.mouse.up();assert.equal(await handle.getAttribute('aria-valuenow'),'228');assert.equal(await handle.getAttribute('data-dragging'),null);
const trigger=sample.getByRole('button',{name:'Open sample panel'});await trigger.click();
const panel=page.getByRole('dialog',{name:'Sample panel'});await panel.waitFor();const note=panel.getByRole('textbox',{name:'Sample note'});await note.fill('Editable anchored content');assert(await panel.isVisible());await page.keyboard.press('Escape');await panel.waitFor({state:'hidden'});assert(await trigger.evaluate(e=>e===document.activeElement));
await sample.getByRole('button',{name:'Show sample notification'}).click();await page.getByText('Sample notification',{exact:true}).waitFor();
await fs.mkdir('/private/tmp/caelos-level1-foundations',{recursive:true});
await sample.screenshot({path:'/private/tmp/caelos-level1-foundations/dark.png'});
await page.getByRole('button',{name:'Switch to light'}).click();await sample.scrollIntoViewIfNeeded();await sample.screenshot({path:'/private/tmp/caelos-level1-foundations/light.png'});
assert.equal(await sample.evaluate(e=>e.closest('[data-caelos-theme]')?.getAttribute('data-caelos-theme')),'light');
await page.setViewportSize({width:390,height:844});await trigger.click();await panel.waitFor();const bounds=await panel.boundingBox();assert(bounds.x>=0 && bounds.x+bounds.width<=390);
await page.emulateMedia({reducedMotion:'reduce'});assert.equal(await panel.evaluate(e=>getComputedStyle(e).animationName),'none');
await page.screenshot({path:'/private/tmp/caelos-level1-foundations/narrow-popover.png'});
await page.keyboard.press('Escape');assert.deepEqual(errors,[]);await browser.close();
console.log('PASS shared foundations: range/checkbox keyboard, progress, resize keys/pointer, editable popover/Escape/focus, notifications, light scope, narrow bounds, reduced motion; zero page errors');
